/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PollParty {
        "host": string;
        "party": string | null;
    }
}
declare global {
    interface HTMLPollPartyElement extends Components.PollParty, HTMLStencilElement {
    }
    var HTMLPollPartyElement: {
        prototype: HTMLPollPartyElement;
        new (): HTMLPollPartyElement;
    };
    interface HTMLElementTagNameMap {
        "poll-party": HTMLPollPartyElement;
    }
}
declare namespace LocalJSX {
    interface PollParty {
        "host"?: string;
        "party"?: string | null;
    }
    interface IntrinsicElements {
        "poll-party": PollParty;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "poll-party": LocalJSX.PollParty & JSXBase.HTMLAttributes<HTMLPollPartyElement>;
        }
    }
}
